# Generated by Django 3.2 on 2022-12-13 06:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50, verbose_name='Nombre de la empresa')),
                ('direccion_empresa', models.CharField(max_length=50, verbose_name='Dirección de la empresa')),
                ('telefono_empresa', models.CharField(max_length=50, verbose_name='Teléfono de la empresa')),
                ('email_empresa', models.EmailField(max_length=50, verbose_name='Email de la empresa')),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_usuario', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('empresa', models.ManyToManyField(to='ticketera.Empresa', verbose_name='Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], verbose_name='Prioridad')),
                ('estado', models.IntegerField(choices=[(1, 'Espera'), (2, 'En curso'), (3, 'Resuelto')], default=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(default=datetime.datetime(2022, 12, 13, 6, 48, 31, 563731, tzinfo=utc), verbose_name='Fecha de creación')),
                ('fecha_cierre', models.DateField(default=datetime.datetime(2023, 1, 12, 6, 48, 31, 563763, tzinfo=utc), verbose_name='Fecha de cierre')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketera.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketera.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
