# Generated by Django 4.1.1 on 2022-12-11 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50, verbose_name='Nombre de la empresa')),
                ('direccion_empresa', models.CharField(max_length=50, verbose_name='Dirección de la empresa')),
                ('telefono_empresa', models.CharField(max_length=50, verbose_name='Teléfono de la empresa')),
                ('email_empresa', models.EmailField(max_length=50, verbose_name='Email de la empresa')),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_usuario', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email_usuario', models.EmailField(max_length=50, verbose_name='Email')),
                ('telefono_usuario', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('nombre_empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('contraseña_usuario', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('prioridad', models.CharField(max_length=50, verbose_name='Prioridad')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('fecha_cierre', models.DateField(verbose_name='Fecha de cierre')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketera.empresa', verbose_name='Empresa')),
                ('usuario', models.ManyToManyField(to='ticketera.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
